-- +goose Up
-- +goose StatementBegin
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS phone_number VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS address VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS gender VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS religion VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS profile_photo VARCHAR(500) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS cover_photo VARCHAR(500) DEFAULT NULL;
-- +goose StatementEnd

